### ISSUE TITLE
Service file to run as service and automatically mount on boot (start, stop, restart, status )

### ISSUE THREAD

**Issue by shivanandsharma** [s3fs-fuse/s3fs-fuse#111]
```
#!/bin/sh

# chkconfig: 2345 20 80
# description: Mounts the S3 bucket varun21-backups to /mys3bucket
# Created by Shivanand Sharma BinaryTurf.Com
# License: GPL 3 and "don't blame me".
# Usage:
#   Edit the relevant sections of this file like your bucket name and mount point
#   copy this file into /etc/init.d/
#   sudo chkconfig --add mounts3
#   sudo service mounts3 start
#   Optional: Configure required runlevels for the service

start() {
echo -n $"Starting..."
sudo s3fs varun21-backups /mys3bucket
sudo ls -al /mys3bucket
}

stop() {
echo -n $"Stopping..."
sudo umount /mys3bucket
}

reload(){
sudo umount /mys3bucket
sudo s3fs varun21-backups /mys3bucket
sudo ls -al /mys3bucket
}

status(){
sudo ls -al /mys3bucket
}

# See how we were called.
case "$1" in
start)
     start
     ;;
stop)
     stop
     ;;
status)
     status
     ;;
restart)
     stop
     start
     ;;
reload)
     reload
     ;;
*)
     echo $"Usage: $prog {start|stop|restart|status}"
     RETVAL=2
esac

exit $RETVAL
```

**Comment by ggtakec** [comment]
Thanks a codes for service.

I'm wander about that normally s3fs should start to run with fstab on boot, do you think about it?
I think that this script is good for not root user, not service.
(for service, I think it is needed to change some(ex, using configuration file instead of bucket name and mount point hard coding))

Regards,

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
I will close this, but if the problem persists, please reopen or post a new issue.

**Comment by abhishekk27** [comment]
I'm still facing the issue, 
s3fs#<bucket-name> <host-folder> fuse retries=5,allow_other,url=https://s3-us-east-2.amazonaws.com 0 0
the mount is unmounting after I boot my server

**Comment by sharmashivanand** [comment]
Have you enabled the service?
Have you updated the bubcket name accordingly?
What is the output of journalctl?

**Comment by abhishekk27** [comment]
yeah, it is working when I'm running 
`sudo mount <folder-name>`
but after the restart, the mount is not present

**Comment by juliogonzalez** [comment]
While the service on the description is nice, it would be way better if it could do some things:

1. Have a variable for the bucketname, and the mount point.
2. Refuse to start if the mount point does not exist, or if can be used for mounting.
3. Support for options.

In fact it should most probably ship an /etc/default/s3fs-fuse file as well.

But all of that should be part of a system package.

Besides of what @ggtakec said, now that a lot of distributions are shipping `systemd` all problems you are having could be because of the way `systemd` is using this `sysvinit` script.

And in the end I am wondering: you have `/etc/fstab`. What's the exactly the use case? Why do you need toi use a service instead of `fstab`? I am sure there's a use case, but can you explain?
