### ISSUE TITLE
Frequent Input/output error

### ISSUE THREAD

**Issue by junaidnasir** [s3fs-fuse/s3fs-fuse#120]
we are trying to move a large number of small files approx. 20 files (100KB) every 2 seconds.
after some time the move operations start piling up and eventually after about 20 minutes s3fs throws an error on any file operation `sudo ls /mnt/bucket
ls: reading directory /mnt/bucket: Input/output error`
in these 20 minutes load average goes from 3 to roughly 8000.
System: Amazon EC2 C3 large
s3fs version: 1.78

**Comment by ggtakec** [comment]
If this reason is timeout error, you can probably solve this by changing the timeout value.
#167 is changed the default timeout value for connecting and reading/writing.
Please try to use latest codes, and if you got same error please retry to run s3fs with connect_timeout and readwrite_timeout options.
thanks in advance for your help.

**Comment by ggtakec** [comment]
I'm closing this issue, if you have a problem yet, please post new issue or reopen this issue.

Thanks in advance for your help.
