### ISSUE TITLE
Commit 045f1e7 breaks s3fs v1.78 on CentOS 5 with CURL v7.19.7

### ISSUE THREAD

**Issue by aplimovil** [s3fs-fuse/s3fs-fuse#126]
Please see this issue reported on Google Code:
https://code.google.com/p/s3fs/issues/detail?id=447

Reverting the aforementioned commit 045f1e7 fixes the issue.

Commit needs to be reviewed to ensure it doesn't breaks compatibility with CentOS5, which comes with CURL v7.19.7.

**Comment by JordanMagnuson** [comment]
Same issue on Ubutun 12.04 with curl 7.22.0:

`s3fs_init(2660): init
InitShareCurl(340): curl_share_setopt(SSL SESSION) returns 1(Unknown share option)
s3fs: Could not initiate curl library.`

Reverting to s3fs v1.77 fixed the problem.

**Comment by ggtakec** [comment]
@JordanMagnuson 
I merged #156 for this issue.
libcurl older than 7.23.0 does not support ssl session shared, so this problem is occurred.
By merged codes s3fs will run with older libcurl.
In other ways, if you do not use ssl session shaing or dns sharing, you can use "nodnscache" and "nosscache" option.(those option are not listed in man page)

Please try to test latest codes, and if you can not run s3fs please post new issue.
Regards,
