### ISSUE TITLE
1.87 release

### ISSUE THREAD

**Issue by tsmgeek** [s3fs-fuse/s3fs-fuse#1335]
I see there are loads of patches and fixes since 1.86 and a major one relates to crashes with stat cache.
When it is likely the next official release will be done as they seem to be far apart.

**Comment by gaul** [comment]
Agreed that 1.87 should release soon, also to align with upcoming Fedora 33 and Ubuntu 20.10 distributions.  Although I would like to investigate #1328 and possibly #1304 before releasing.  @ggtakec do you have any other wish list issues, maybe #1332?  I can prepare the next release if you would like.

**Comment by ggtakec** [comment]
@gaul I also wished to release it.
For my wishlist, it's #1334.(I believe it will provide a means of checking for cached file issues if the cache will have something wrong.)

I think #1332 should not be included in this release, because it will take time to create a stack trace and that it will be provided like an option that is used only when debugging even if it is implemented.

About #1304, it has been fixed in #1313. I think it's the same cause.

#1328 can be solved if it is the same problem as #1319, but if it needs nocopyapi when using Scaleway, the problem of traffic cannot be solved. (Because the data is downloaded once to the localhost side and then uploaded, the communication volume increases.)

I leave comments for each of these issues.

**Comment by gaul** [comment]
@ggtakec I can run the release during the holiday next weekend if this is OK.  What do you think?

**Comment by ggtakec** [comment]
@gaul Sounds good.
Let's launch it next weekend.
I'll clean up some PRs, so it's after that.
Please wait a moment.

**Comment by ggtakec** [comment]
Thanks for release 1.87, we start new version.

**Comment by juliogonzalez** [comment]
As always, here I will post here the URLs with the submissions to openSUSE/SLE and Fedora EPEL.

openSUSE/SLE: https://build.opensuse.org/request/show/825431 (as always: this is the devel project, from there it should eventually get into openSUSE Factory and then into Leap and SLE)

**Comment by gaul** [comment]
I filed an issue to upgrade Ubuntu:

https://bugs.launchpad.net/ubuntu/+source/s3fs-fuse/+bug/1891124

**Comment by ggtakec** [comment]
@juliogonzalez @gaul Thanks a lot.

And, it may be multiple contacts, but we will also mention them.

@mapreri @jollyroger
I apologize for not contacting immediately.
Version 1.87 has been released, so I will mention it.
Regards,

**Comment by mapreri** [comment]
Hi!

Somebody wrote a launchpad bug before I even noticed the new release, so
yesterday I already uploaded 1.87 to Debian unstable.

o/

**Comment by ggtakec** [comment]
@mapreri Thanks for your kindness.
