### ISSUE TITLE
rename_before_close failure

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#145]
```
$ make check -C test
...
rename_before_close: rename_before_close.c:46: test_rename_before_close: Assertion `get_file_size(template) == sizeof(FILE_CONTENT)' failed.
./integration-test-main.sh: line 274: 18749 Aborted                 (core dumped) $CUR_DIR/rename_before_close $TEST_TEXT_FILE
```

@kahing Can you investigate?

**Comment by andrewgaul** [comment]
Note that I tested with s3proxy-1.4.0-20150307.195914-6-jar-with-dependencies.jar, not 1.3.0 release.

**Comment by kahing** [comment]
I got failure before it gets to that test:

```
Testing mv file function ...
moved file length is not as expected expected: 12  got: 0
```

Looking...

**Comment by andrewgaul** [comment]
Sorry we need to merge #147 to avoid the first set of failures.

**Comment by kahing** [comment]
confirmed that #147 fixes the first rename problem. confirmed that the rename_before_close test fails with real S3 as well

**Comment by kahing** [comment]
regression caused by #138. Reverting the no_cache prefix changes fixes this problem.

I am not sure what the no_cache prefix change is intended to fix, why wouldn't we always want to use the same FdEntity?

**Comment by ggtakec** [comment]
@kahing I meged fixed code to master branch now.
This problem is occurred by s3fs does not have fsync handler. so fsync event could not be caught by s3fs.
Before #138, s3fs could not disable the use_cache, in order to have continued to share the file handle, had happened fsync functions. After fixing #138, poblem of this issue was apparent.
Probably #150 fixed this issue.

@andrewgaul @kahing  thanks a lot.

if this merge can fix all of this issue, please close this issue.
Regards,

**Comment by ggtakec** [comment]
I close this issue.
If you continue to not solve this problem, please reopen this issue.
Thanks a lot.

**Comment by kahing** [comment]
master still fails the rename_before_close test

**Comment by andrewgaul** [comment]
@ggtakec Please reopen this issue -- we lack the karma to do so.

**Comment by ggtakec** [comment]
# 898 has been merged.
