### ISSUE TITLE
How to Install s3fs in OS/390 

### ISSUE THREAD

**Issue by prasad-1729** [s3fs-fuse/s3fs-fuse#1521]
Hi,

Is there a way to install s3fs in OS/390 ??
can you please suggest us?

Thanks!!

**Comment by gaul** [comment]
Does OS/390 have a FUSE driver?

**Comment by prasad-1729** [comment]
Hi @gaul 

No idea, 
how to check it whether FUSE driver is there or not?

thanks!

**Comment by gaul** [comment]
Sorry I don't know anything about the IBM mainframe ecosystem.  Wikipedia suggests that [OS/390](https://en.wikipedia.org/wiki/OS/390) is its own operating system that is discontinued and succeeded by [z/OS](https://en.wikipedia.org/wiki/Z/OS).  It seems doubtful that this has a FUSE driver but maybe you can install it in a guest Linux VM?  It also appears that the underlying [S/390](https://en.wikipedia.org/wiki/IBM_System/390) hardware has a [Debian port](https://www.debian.org/ports/s390/) if this is what you are doing.

@orozery Maybe you can help out with some of the terminology here?

**Comment by juliogonzalez** [comment]
Fuse is available at current Debian Stable for s390x: https://packages.debian.org/buster/fuse-modules-4.19.0-13-s390x-di

And I also confirm that it's available on SLE12/SLE15 s390x. 

In the end, a recent FUSE (required to build and run s3fs-fuse) should be able to build and run at any recent GNU/Linux distribution for almost every architecture, as it doesn't seem the Linux doc mentions any exception for the FUSE module (https://www.kernel.org/doc/html/latest/filesystems/fuse.html)

It seems is FUSE (and compatible implementations) also for, *BSD, MacOS (mentioned on the README for s3fs-fuse) and even GNU/Hurd and Windows (in this last case seems to be proprietary and paid).

For OS/390, even without being familiar with the OS: I find hard to believe there will be any FUSE implementation, since I found news that mention that IBM stopped selling it on December 2002 and the OS got finally discontinued and unsupported in September 2004. The oldest FUSE version (https://github.com/libfuse/libfuse/blob/fuse_2_9_3/ChangeLog) seems to be from late 2000/first months of 2001.

For z/OS, no idea. But if I need to bet some money, I have my doubts about any free software reimplementation of FUSE being available... and I even have my doubts that there will be something proprietary that can be bought.

**Comment by prasad-1729** [comment]
Thank you @juliogonzalez @gaul for your inputs..!
