### ISSUE TITLE
[Question]multiple clients mounting the same bucket

### ISSUE THREAD

**Issue by GoTheExtraMile** [s3fs-fuse/s3fs-fuse#1611]
Hi ! 
in limitations your say :

` 
 - non-AWS providers may have eventual consistency so reads can temporarily yield stale data (AWS offers read-after-write consistency since Dec 2020)
 - no coordination between multiple clients mounting the same bucket
 `
Can I think that when using Amazon storage, it is highly consistent for multiple clients to mount the same bucket?

**Comment by gaul** [comment]
s3fs has other sources of inconsistency due to caching.  For example, if client1 calls stat on a file then client2 appends to it, client1 will see the old metadata until `stat_cache_expire` expires, by default 900 seconds.  Even if you reduce this to 0 there is no coordination between the s3fs clients.  In other network file systems like SMB2, a client can create leases to files which ensures that other clients cannot access them until the lease expires or is revoked.

**Comment by GoTheExtraMile** [comment]
thanks
