### ISSUE TITLE
Upgrade macOS CI 

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1769]
I saw this warning today:

> macOS-latest workflows will use macOS-11 soon. For more details, see https://github.com/actions/virtual-environments/issues/4060

But I believe that osxfuse does not support macOS 11 or requires some rebooting or other difficulties.

**Comment by ggtakec** [comment]
@gaul Thanks for your infromation.
I would be happy if following problem was solved.
I will try it once around 11/3.
https://github.com/s3fs-fuse/s3fs-fuse/blob/master/.github/workflows/ci.yml#L120-L126

**Comment by ggtakec** [comment]
I noticed the following error for macos in the Schedule build of Github Actions on this Sunday.
```
configure: error: Package requirements (fuse >= 2.7.3 libcurl >= 7.0 libxml-2.0 >= 2.6 libcrypto >= 0.9 ) were not met:
No package 'libcrypto' found
```

**Comment by ggtakec** [comment]
**The macOS 10.15 Actions runner image will be fully unsupported by 8/30/22 in GitHub**

I've picked up this issue from the Issue at https://github.com/actions/virtual-environments/issues/5583.
And today I saw an errors about this several times, when the test run on macOS runner.

Currently, Github Actions for s3fs test has no choice but to use macOS 10.15. That's because we get an error when installing osxfuse if we use another macOS version.
See: https://github.com/actions/virtual-environments/issues/598 , https://github.com/actions/virtual-environments/issues/4731

We need to install osxfuse on macOS11 runner, but we can not have done it yet.

**Comment by ggtakec** [comment]
Currently, in Github Action, the following error is displayed and it can not be solved.
> This is a scheduled macOS-10.15 brownout. The macOS-10.15 environment is deprecated and will be removed on August 30th, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5583

**Comment by ggtakec** [comment]
Since `macos-12` Github Actions runner is now supported, I checked again with both `macos-11` and `12`.

In conclusion, it is unlikely that you can install and use `macfuse` with Github Actions Runner.
This is because `macfuse` is not allowed in macOS device policies, so it cannot be used without rebooting.

For reference, if your macOS device policies are allowed, you can view them like this:
```
$ sudo sqlite3 /private/var/db/SystemPolicyConfiguration/KextPolicy "select * from kext_policy;"
   3T5GSNBU6W|com.github.osxfuse.filesystems.osxfuse|1|Benjamin Fleischer|5
   3T5GSNBU6W|io.macfuse.filesystems.macfuse|1|Benjamin Fleischer|1
```

Once support for macos-10 ends, we won't be able to test with GithubActions on macos.

**Comment by ggtakec** [comment]
The macos10 runner no longer runs as planned.
First, I made macos10 not reqired from "Status checks that are required".

**Comment by ggtakec** [comment]
Although macos10 for our Actions has been removed from the requirement, runners on macos10 will be available until December 1, 2022.
(no workaround yet)

**Comment by ggtakec** [comment]
As of May 2023, it is no longer possible to launch macOS 10.15 as a Runner for Github Actions.
After this, it is necessary to use macOS 11 or later, but Github Actions cannot be executed because the OS reboot is required to install macFUSE.
Therefore, PR #2154 disabled running Github Actions on macOS.

We will resume this once we are able to work around the macFUSE installation issue on macOS 11 and above.

I close this Issue, but I hope to reopen this for re-enabling macOS.
