### ISSUE TITLE
s3fs benchmark testing tools

### ISSUE THREAD

**Issue by syu-lk4b** [s3fs-fuse/s3fs-fuse#1808]
We are trying check the performance compare with other storage , do we have a recommend benchmark testing tools . I am currently using "https://github.com/axboe/fio" ,but maybe this is not a correct tools.  Basically we are trying to use s3fs-fuse to mount the s3 bucket for Machine learning training.   We have enabled the local cache , but after almost everything get cached, there are still some gaps ,compare with local storage, even everything is already cached in local storage

**Comment by gaul** [comment]
s3fs does not focus on performance but we look at the [goofys benchmarks](https://github.com/kahing/goofys) since this is a high-quality implementation.  Note that its published benchmarks are 2 years out of date and don't reflect the current s3fs performance: kahing/goofys#647.  It would be great if you could publish a blog post comparing s3fs, goofys, or other FUSE filesystems using fio, goofys benchmark, or something else!

Local storage will always be faster that s3fs even when the cache is working.  The local filesystem uses the kernel cache while s3fs uses a user-mode cache so there are overheads.  That said there might be inefficiencies if you can point to some specific case that caching does not work as you expect.

**Comment by Stevenyu1982** [comment]
@gaul thanks so much. I'll definitely post a blog once i finished the benchmark testing

**Comment by ggtakec** [comment]
Close this issue. If you still need it, please reopen it.
