### ISSUE TITLE
Do we have to flush on s3fs_truncate?

### ISSUE THREAD

**Issue by orozery** [s3fs-fuse/s3fs-fuse#1875]
We have an application which writes large files (~4GB) in 32MB chunks,
where before each 32MB write, the application is calling `ftruncate` to increase the file size by 32MB.
This maps to `s3fs_truncate`, which flushes the file.
The writing to the S3 backend becomes very inefficient, as the entire file is overwritten every 32MBs written.

I'm wondering if the flush on `s3fs_truncate` can be avoided.
In the man page of ftruncate, I did not see they mention that a flush is guaranteed.

@gaul will be happy to get your thoughts.
Thanks!

**Comment by gaul** [comment]
I believe that s3fs has always `fsync` on `ftruncate`, as far back as 4a30df1ff24aeac92d3ab0f8e84b34df8e70ec3d.  I do not believe that POSIX actually requires this and the slower implementation was only a reflection of s3fs' limited dirty data tracking at that time.  Since `ftruncate` is an uncommon operation we have not optimized it yet.  Could you submit a PR for this?

**Comment by gaul** [comment]
One thing to investigate is whether s3fs calls `ftruncate` on its temporary file so that it can return `ENOSPC` to the application if local storage is too small.

**Comment by ggtakec** [comment]
I think we need to re-check the code that uses the file size after truncate operation.
The file size is used by other operations that occur after truncate. (In various places)

For example, when using a cache file(in the case where there is a directory capacity), it tries to substitute the file size acquisition from the local cache file.
However, if the cache is not used, the current s3fs will have a problem if the size is not reflected in the S3 server side object after calling the truncate operation.

However, we may be able to turn off fsync while the file is open.
(But that doesn't seem to be a simple fix.)

**Comment by gaul** [comment]
If we added performance counters, suggested in #1571, we could modify the integration tests to check the expected number of RPCs.  This would ensure that we are not regressing performance on operations like truncate.

**Comment by ggtakec** [comment]
As you say, performance evaluation for cache is necessary.
(Let's define what should be measured in #1571)

In the first comment of @orozery, there is the following sentence.
> where before each 32MB write, the application is calling ftruncate to increase the file size by 32MB.
> This maps to s3fs_truncate, which flushes the file.

In other words, the application repeates call truncate->write pair.
s3fs(and FUSE) does not know that write will be called after truncate.
That's why in the current implementation, it's flushing at every trauncate...

If you want to avoid this, we will be ables to change s3fs as:
only at the close(flush/release) is called, s3fs outputs all dirty parts at once.
But I think that this workaround cannot be used when the local cache is not used (cannot be created).
Conversely, in situations where the local cache is available, it may be possible to prevent flushing until close.

**Comment by orozery** [comment]
I'm trying to re-think this whole idea.
If the user is using `ftruncate`, it makes sense to not flush, and wait for `flush` or `close`.
However, if the user is using `truncate`, which does not get a file descriptor, then I think he should expect the truncate to be immediate on the S3 server.

With the current `s3fs_truncate` we cannot tell if truncate was called on a file handle (and which).

Now I see that in FUSE3 they changed `int (*truncate) (const char *, off_t)` to `int (*truncate) (const char *, off_t, struct fuse_file_info *fi)`.
Specifically here:
https://github.com/libfuse/libfuse/issues/58

I guess s3fs is configured with FUSE2 which does not have this new API?

**Comment by ggtakec** [comment]
_For details, on the premise that you have to check the source code._

s3fs has been modified to use an internally temporary file descriptor(which is a number that is recognized only inside s3fs, not the fd issued by the system) when a file is opened.
So I think I can use this temporary file descriptor to determine if it's an open file.

**Comment by gaul** [comment]
While s3fs should optimize `truncate`, should your application call `posix_fallocate` instead?

**Comment by orozery** [comment]
> While s3fs should optimize `truncate`, should your application call `posix_fallocate` instead?

Well, my application is closed-source (Symantec) Ghost, so I cannot control its posix calls.
But even though, s3fs currently does not implement `fuse_operations.fallocate`.

**Comment by ggtakec** [comment]
I think it is possible to implement fuse_operations.fallocate in s3fs.
(it is depending on the mode flags, the implementation can be difficault)

Do you intend to solve this problem by setting(keeping) the file size with fallocate and then writing additional data?

**Comment by orozery** [comment]
> I think it is possible to implement fuse_operations.fallocate in s3fs. (it is depending on the mode flags, the implementation can be difficault)
> 
> Do you intend to solve this problem by setting(keeping) the file size with fallocate and then writing additional data?

As I said, I cannot control the application, which uses `ftruncate`.
The only option I see is to change s3fs from `libfuse-dev` to `libfuse3-dev`. Have we considered this?

**Comment by gaul** [comment]
@orozery Please test your application with the latest master and report if this addresses your symptoms.
