### ISSUE TITLE
Consider changing `-o noobj_cache` default

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1901]
Currently the `noobj_cache` is disabled but we should consider enabling it by default, similar to #927.  I am not sure if we need a mechanism to disable it?

**Comment by ggtakec** [comment]
I agree with enabling it.
But, if we enable the default value, there may be some user(how many users?) confusion.
(It is Imagined that the degree of influence is proportional to the default value of the cache expiration time.)
I think we need to know how many users would be affected ...

In order to disable it, we need to prepare a dedicated option(ex. `disable_noobj_cache`) and so on.
(Now we have created option names when it is needed, there is no uniformity in option names. So I would like to organize the options as a whole, including the option names.)

**Comment by gaul** [comment]
6b78bfdf4b504629aa36d127ed1b3dbd6d44312b added this flag in 2013 but does not discuss the default behavior.  I think that if we can understand the impact on users via tests like #1900 (and possibly more) then we can have confidence to change the default.  Agree that adding a flag to restore the current behavior is a safe idea.  Probably better to change these kinds of defaults soon after a release to give the most testing time.
