### ISSUE TITLE
test_mtime_file and test_update_time_cp_p fail on Fedora

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1959]
This appears to be due to unexpected ACL syscalls which change ctime and atime:

```
fgetxattr(3, "system.posix_acl_access", 0x7ffc66203b90, 132) = -1 ENODATA (No data available)
fsetxattr(4, "system.posix_acl_access", "\2\0\0\0\1\0\6\0\377\377\377\377\4\0\4\0\377\377\377\377 \0\0\0\377\377\377\377", 28, 0) = 0
...
cp with -p option expected updated ctime: 1000000000 != 1655037804 and same mtime: 1000000000 == 1000000000, atime: 1000000000 == 1655037804
```

**Comment by ggtakec** [comment]
Does it mean that `atime` has been updated because `fsetxattr` was called?
Is it possible that `xattr` is set in the copy source file?
I set `xattr` in the source file and tried it with AMI, but `xattr` was not set in the destination file, and there was no `atime` change.

It seems that we need to find out why this problem occurred only in Fedora.

**Comment by ggtakec** [comment]
This issue doesn't seem to be happening now.
(At the moment, CI is successful on Fedora36/37)
This will be closed. If you still have problems, please reopen or post a new issue.
