### ISSUE TITLE
Release 1.79

### ISSUE THREAD

**Issue by andrewgaul** [s3fs-fuse/s3fs-fuse#206]
s3fs has many commits since last September: https://github.com/s3fs-fuse/s3fs-fuse/compare/v1.78...master

including support for V4 signing, GovCloud, xattrs, special characters, and fixing many bugs including a data corruption issue #64.  The only blocking issue I see is #203 which could change the format of extended attributes.

**Comment by ggtakec** [comment]
@andrewgaul 
I am also want to as soon as possible for the next version release.
There is also Issue of still being confirmed (no reply), I was hesitant.
Because it is a new problem also it seems like does not occur, so that I will make new release at this weekend.
About #203, if it need to change format, it will fix next release after v1.79.
If you have a problem, please let me know.
Regards,

**Comment by kahing** [comment]
If #203 changes the format, doesn't it make sense to fix it before the next release, so that s3fs doesn't behave differently across versions? Otherwise people upgrading from 1.79 to the next version will have problems.

**Comment by ggtakec** [comment]
@kahing 
I think we can keep compatibility between v1.79 and the newer version  which is changed about xattr http header if it is needed.

About #203, I think it does not need to change the header name for xattr, because s3cmd and AWS console should modify x-amz-meta-xattr header if user need to change.
For details, I will comment on #203 issue.

So I would make new release because we can keep compatibility regardless of the result of #203.

Thanks a lot.

**Comment by ggtakec** [comment]
Hi, all
I wait to build v1.79 release until #203 issue is resolved.
Regards,

**Comment by ggtakec** [comment]
Hi, all
Uploaded new release v1.79.
If you found a problem and issues, please post new issue.

Thanks in advance for your assistance.
