### ISSUE TITLE
Add `run_tests_using_sanitizers.sh` to CI

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#2172]
This will help avoid memory and thread safety regressions.  We only need to run these on one distro, e.g., Fedora 38.

**Comment by ggtakec** [comment]
I posted Draft PR #2173 for this issue.

I considered the code to call `run_tests_using_sanitizers.sh` but gave up and wrote it directly in `ci.yaml`.
That is each test in `run_tests_using_sanitizers.sh` seem best to be a CI Job because all of test several patterns require execution from the build.
And the testing base container is Ubuntu:22.04.

However, some test results are failing, so I think it is necessary to modify the source code. (This is one of the reasons why it is a draft.)

Please check and review it.

**Comment by ggtakec** [comment]
Additinal Information about #2173 
- The `valgrind` test is taking too long (maybe not finished) and has been aborted by manual.
- The `sanitaize thread/memory` test is failing.

**Comment by ggtakec** [comment]
This issue is closed.
ThreadSanitizer tests still detect errors, which are discussed in #2220.
