### ISSUE TITLE
Readdir result misses certain dir in 1.92 version

### ISSUE THREAD

**Issue by hbao0915** [s3fs-fuse/s3fs-fuse#2393]
#### Version of s3fs being used (`s3fs --version`)
V1.92 (commit:unknown) with OpenSSL

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)
2.9.9

#### Kernel information (`uname -r`)
5.4.0-153-generic

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

#### How to run s3fs, if applicable
/root/s3fs-fuse-1.92/src/s3fs test-list /mnt/test -o passwd_file=/root/aksk -o url=https://obs.cn-south-1.myhuaweicloud.com -o compat_dir

### Details about issue
`mkdir /mnt/test/b` (/mnt/test is the MOUNTPOINT)
`touch  /mnt/test/b/file`
Then use SDK to create a object named `/ab/cd`.

(There should be 3 objects in the backend storage server, `/b`, `/b/file` and `/ab/cd`.)

At last, readdir to the mountpoint root directory, the result expects to be `b` and `ab`, BUT it only shows `b`.

**Comment by hbao0915** [comment]
I did some more testing, and found that if I remove `/b/file`, the readdir result becomes correct.

**Comment by ggtakec** [comment]
@hbao0915 
Around v1.91, the handling of objects created from SDKs other than s3fs is slightly different.(These are related to the `compat_dir` option, etc.)
s3fs performs processing to detect objects (including directory paths) created with SDK(aws CLI), etc.

If possible, try using the code from the master branch or restarting it with the compat_dir option.
With the current master code, this issue seems to have been resolved.

**Comment by hbao0915** [comment]
1.93 version seems fine according to my test scenario, thx
