### ISSUE TITLE
s3fs appears to crash on ls with permission failure

### ISSUE THREAD

**Issue by rpattcorner** [s3fs-fuse/s3fs-fuse#25]
Use case:
* S3fs latest as of 3/23/14, e.g. 1.74
* Arrange s3 bucket and iam role permissions for account a to write account b bucket (we wrote to a top level pseudo-folder, e.g. "files/whatever"
* Copy files from a to b with a 'brute force' tool like aws cli (sync or copy)
* Observe that the ACL on account b does not have account b owner rights ACL (because account a wrote the file)

Now ... 
List the top level bucket with s3fs and see s3fs is working
List the top level folder and observe the segfault
Mar 23 11:44:52 ip-10-0-0-62 kernel: s3fs[23263]: segfault at 0 ip 0000000000423639 sp 00007f9a1ee22760 error 4 in s3fs[400000+51000]

Thing is ... s3fs will segfault if **any** file in a listing fails permissions in this way.
Suggested fix:
* Catch and trap any ACL error
* Print out message object: XXXX cannot be (whatever the operation was)
* Continue to next operation

**Comment by ggtakec** [comment]
I'm sorry about this Issue had been left at a long period of time.

If you have this problem yet, please try to use latest code because some problem about multipart request etc were fixed.
("-f", "dbglevel" and "curldbg" options help to solve your problem.)
And if you found a problem, please post new issue.

Thanks in advance for your help.
