### ISSUE TITLE
Freebsd 14.1 Abort trap (core dumped)

### ISSUE THREAD

**Issue by konovalovk** [s3fs-fuse/s3fs-fuse#2514]
#### Version of s3fs being used (`s3fs --version`)
1.92_1

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)
2.9.9_2

#### Kernel information (`uname -r`)
14.1-RELEASE-p3

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)
NAME=FreeBSD
VERSION="14.1-RELEASE-p3"
VERSION_ID="14.1"
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 14.1-RELEASE-p3"
CPE_NAME="cpe:/o:freebsd:freebsd:14.1"
HOME_URL="https://FreeBSD.org/"
BUG_REPORT_URL="https://bugs.FreeBSD.org/"

#### How to run s3fs, if applicable
as 14.0 where it works without Abort trap (core dumped)

### Details about issue
Running clean s3fs command or full mount command ends with "Abort trap (core dumped)" error on freebsd 14.1. Tested on clear installation.

**Comment by gaul** [comment]
Can you try with the latest 1.94 or master?  Also how did you get version 1.92?  The official package appears to be 1.89 which is another problem: https://svnweb.freebsd.org/ports/head/sysutils/fusefs-s3fs/.  I would like to improve FreeBSD support but I don't use it myself and don't really understand what is broken, e.g., #2181.  PRs welcome!

**Comment by konovalovk** [comment]
Both port build and pkg installation give outdated 1.92_1 version
https://www.freshports.org/sysutils/fusefs-s3fs

The commands to reproduce
```
pkg install fusefs-s3fs
kldload fusefs
cd ~
mkdir test
s3fs xxx test -o passwd_file=xxx -o url=xxx -o use_path_request_style
```

**Comment by konovalovk** [comment]
Digging... Let it stay here https://mm.icann.org/pipermail/tz/2024-January/033488.html
strftime was affected ≥14.1

**Comment by gaul** [comment]
I don't understand your comment since s3fs does not call `strftime` with `%s`:

```
src/s3fs_logger.cpp:        strftime(tmp, sizeof(tmp), "%Y-%m-%dT%H:%M:%S", gmtime_r(&now.tv_sec, &res));
src/string_util.cpp:    strftime(buf, sizeof(buf), "%a, %d %b %Y %H:%M:%S GMT", gmtime_r(&t, &res));
src/string_util.cpp:    strftime(buf, sizeof(buf), "%Y%m%d", gmtime_r(&tm, &res));
src/string_util.cpp:    strftime(buf, sizeof(buf), "%Y%m%dT%H%M%SZ", gmtime_r(&tm, &res));
```

We cannot support anything other than the latest release version 1.94 or master.  Please ask FreeBSD to update to the latest or compile yourself from source.

**Comment by brett-rickman** [comment]
I downloaded and tried to compile version 1.94 on FreeBSD 14.1-RELEASE.  I had to make the following changes to src/s3fs.cpp and src/s3fs_util.cpp to get it to compile and run:

-- src/s3fs.cpp        2024-08-22 09:01:16.671914000 +0000
+++ ../s3fs-fuse-fixed/src/s3fs.cpp     2024-08-21 23:04:41.724662000 +0000
@@ -30,6 +30,7 @@
 #include <dirent.h>
 #include <sys/types.h>
 #include <getopt.h>
+#include <sys/wait.h>

--- src/s3fs_util.cpp   2024-08-22 09:01:16.672572000 +0000
+++ ../s3fs-fuse-fixed/src/s3fs_util.cpp        2024-08-21 23:40:11.903323000 +0000
@@ -70,7 +70,7 @@
     if(0 > res){
         if (errno != 0){
             S3FS_PRN_WARN("could not get max pw length.");
-            abort();
+            // abort();
         }
         res = 1024; // default initial length
     }
@@ -80,7 +80,7 @@
     if(0 > res) {
         if (errno != 0) {
             S3FS_PRN_ERR("could not get max name length.");
-            abort();
+            // abort();
         }
         res = 1024; // default initial length
     }

It appears the abort() is caused by the a failure and errno being returned by the calls in init_sysconf_vars() for _SC_GETPW_R_SIZE_MAX and _SC_GETGR_R_SIZE_MAX. If either of these returns -1 with an errno, the function aborts. 

As a test, I was able to get version 1.94 to run by simply commenting out the calls to abort().

**Comment by gaul** [comment]
The man page suggests that the call to `sysconf` is not handling `errno` properly:

> If name corresponds to a maximum or minimum limit, and that limit is indeterminate, -1 is returned and errno is not changed.  (To distinguish an indeterminate limit from an error, set errno to zero before the call, and then check whether errno is nonzero when -1 is returned.)

**Comment by ivomarino** [comment]
will a new package be available soon? Still had the same issue just today on 14.1, thanks for info

**Comment by konovalovk** [comment]
Now it is the turn of the maintainers of https://www.freshports.org/sysutils/fusefs-s3fs

**Comment by gaul** [comment]
Can someone open a FreeBSD bug report or send a mail to the package maintainer?  The 1.92 package is useless for users.  Please share a link to the report or mail here so we can track it.

**Comment by ivomarino** [comment]
> Can someone open a FreeBSD bug report or send a mail to the package maintainer? The 1.92 package is useless for users. Please share a link to the report or mail here so we can track it.

done, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281071#c1

**Comment by devnull-hub-lab** [comment]
Committed

https://cgit.freebsd.org/ports/commit/?id=36ce604a8ee4d921ca8aff0bbb83e3a209fa3905
