### ISSUE TITLE
Can't access to my bucket. 

### ISSUE THREAD

**Issue by m27387** [s3fs-fuse/s3fs-fuse#314]
20151205.20:24 GMT +8
After google for half a day I found that using s3fs under Debian server would occasionally occurred "RequestTimeTooSkewed" issue. This (http://www.emind.co/how-to/how-to-fix-amazon-s3-requesttimetooskewed) could fix it.

I can now mount my bucket to any mountpoint in my local server. The current problem now is that it can't be set to mount automatically on boot. After rebooting my server, the ownership and permissions to my mountpoint became question marks (like this: http://media.hi-check.com/2015/12/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88-2015-12-05-14.26.17.png) I have to umount the mountpoint and using s3fs command manually to make them connect. 

According to https://github.com/s3fs-fuse/s3fs-fuse , I inserted a line to my fstab like this: s3fs#mybucket /path/to/mountpoint fuse _netdev,allow_other 0 0

is there any missing parts in my process? 
Thanks for your help!

---

Original post
Hi there,
My s3fs suddenly crashed and when I checked the ownerships and permissions, there were only question marks. (like this: http://www.hi-check.com/media2/2015/12/スクリーンショット-2015-12-05-14.26.17.png)

And I checked the installation tutorial and used debug command. It seemed s3fs changed my AWS server location from Singapore to US. (like this: http://www.hi-check.com/media2/2015/12/スクリーンショット-2015-12-05-14.27.14.png)

Is there anyway to fix it. thanks!

**Comment by RobbKistler** [comment]
So the mountpoint is actually running after you reboot, but?  Can you paste the output of `mount` after start-up?  And the command you are using to manually restart it? 

The question marks in the ownership and permissions is probably the result of objects that were not placed in the bucket by s3fs-fuse originally.  You may need to remove the objects via some other tool like the AWS management console.

If the unix credentials aren't important to you, use FUSE mount options to force the values.  Something like
```
-ouid=1000 -ogid=1000 -oumask=0
```
Check /etc/passwd for the values to use for uid and gid.  A umask of zero just opens everything up for read/write/execute.  

I see that s3fs-fuse has its own notion of uid, gid and umask options that would only take effect if the object is missing its metadata.  It doesn't seem possible to actually active them because they collide with the FUSE command-line options.  I'll investigate that.

**Comment by TenaciousMel** [comment]
Here's an attachment of my mounted volume on boot.
I set a cron job to automount my bucket and here's the file:
mkdir /mnt/s3-drive
/usr/bin/s3fs media.hi-check.com /home/checkma/www/media -o
allow_other,nonempty,multireq_max=5

did you mean that I have to put "-ouid=1000 -ogid=1000 -oumask=0" in the
end of the second line making it like:
/usr/bin/s3fs media.hi-check.com /home/checkma/www/media -o
allow_other,nonempty,multireq_max=5,ouid=1000,ogid=1000,oumask=0

thanks for the reply.
[image: 內置圖片 1]

Lai, Shao-Yi

2015-12-11 22:24 GMT+08:00 Robb Kistler <notifications@github.com>:

**Comment by ggtakec** [comment]
To know which part on whether an error has occurred, please try the following options.
About "dbglevel" and "curldbg" option, these option can be used in booting, and s3fs will put logs to syslog.
Probably the log helps us for solving this issue.

If you are looking at the directory which permission is listed as 000, I think that it is not a directory created by s3fs.
(another tools creates objects on s3 without metadata for s3fs)
Please try to properly set the directory permissions, such as in chmod.
Or, please try to specify options such as umask.

Thanks in advance for your help.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
