### ISSUE TITLE
Ignore files

### ISSUE THREAD

**Issue by Mambix** [s3fs-fuse/s3fs-fuse#316]
Is there a mechanism to ignore certain files?

For example I'm using this for btsync folder and it doesn't need to sync *.bts files to S3 bucket necause they are still beeing synced between machines. Once btsync does it's job it will rename the file and so it will be ready to sync to S3.

**Comment by RobbKistler** [comment]
s3fs-fuse doesn't have a mechanism to do that.

**Comment by RobbKistler** [comment]
You might check out http://filterfs.sourceforge.net.  It could work in conjunction with s3fs-fuse to give you the functionality you want.  The performance might not be great.

**Comment by Mambix** [comment]
Thanks @RobbKistler that might just work.
It's painfully slow atm, but this might be exactly what I need

**Comment by ggtakec** [comment]
@Mambix 
@RobbKistler said correct, s3fs does not support the filter of the file directory, because it only supports transparent access to S3 object.
If you can be set to overlap the filterfs and s3fs, it might be realized.

I close this issue, but if you have a problem, please reopen this issue.
Thanks in advance for your help.
