### ISSUE TITLE
Permission denied trying to access file in bucket

### ISSUE THREAD

**Issue by martyychang** [s3fs-fuse/s3fs-fuse#333]
After mounting the bucket with following command, I'm getting "permission denied" errors when trying to access files in the bucket. For example:

```
$ cp mount/point/anyfile.txt .
cp: cannot open ‘mount/point/anyfile.txt’ for reading: Permission denied
```

If I look at the permissions on a file through the mount point, I see:

```
$ ls -l mount/point/anyfile.txt
---------- 1 root root 5796 Nov  6 08:47 mount/point/anyfile.txt
```

What might be causing this symptom? The command I'm using to mount S3 is shown below.

```
$ s3fs -o use_path_request_style -o url=http://s3.amazonaws.com my.bucket:/myfolder mount/point/
```

**Comment by ggtakec** [comment]
@martyychang 
Probabry, mount/point/anyfile.txt was uploaded by other S3 tools(s3cmd, s3 console, etc)

s3fs needs x-amz-meta-*(mode,uid,gid,mtime) HTTP headers for permission like filesystem.
Cause of this "----------" permission which you saw is that the object(anyfile.txt) does not have x-amz-meta-mode, or there is no object for "point" directory.

To solve the problem, you need to set the HTTP headers that is required by the s3fs.
You re-upload objects with custom headers by other tools, or you can set attributes for objects by s3fs(ex. chmod 777 mount/point; chmod 666 mount/point/anyfile.txt).


s3fs supports objects that have been uploaded by other tools as much as possible, but this issue is can only be resolved in this way now.

Regards,

**Comment by timduly4** [comment]
Hi there,

I was having trouble with these permissions and I thought I would give a concrete solution example of uploading a file with `boto3` (*important:* version 1.4, see here: https://github.com/boto/boto3/issues/389#issuecomment-237610668):

```
import boto3 # 1.4
import botocore

s3 = boto3.resource('s3')

s3.meta.client.upload_file('file.txt', 'my_bucket', 's3-file.txt',\
        ExtraArgs={
            "Metadata": {
                "mode": "33204",
                "uid": "1000",
                "gid": "1000",
                },
            },)
```

The mode, uid, and gid numbers (33204, 1000, and 1000, respectively) are a bit mysterious to me. I was able to discern that (33204)_10 ~ (664)_8, but can't understand '1000'.

I was able to obtain these numbers by reverse engineering: I `chmod` and `chown` on the s3fs-mounted file to my liking (e.g., 664 and ubuntu), then looked at the metadata via:

```
import boto3
from pprint import pprint

s3 = boto3.resource('s3')
object = s3.Object('my-bucket', 'my-key')
pprint(object.metadata)
```

Output:

```
{'gid': '1000', 'mode': '33204', 'uid': '1000'}
```

Hope this helps!

**Comment by skliarie** [comment]
There is a way to replace metadata without re-uploading the whole object:
http://stackoverflow.com/questions/269840/is-it-possible-to-change-headers-on-an-s3-object-without-downloading-the-entire

BTW, chmod suggestion above does not work for files bigger than 5 GB and even then it takes time proportionally to the file size.

**Comment by dsulli99** [comment]
@ggtakec I can't the chmod commands to work on OS X (for s3 objects), even with the bucket mounted as superuser.  I get `Operation not permitted`. I've tried chmodding the mount point to 777 and re-mounting, still no dice.  I'm mounting with:

`s3fs bucket /mnt/bucket`

I'd be interested in how to get this to work.

**Comment by wenhongqiang** [comment]
anyone can figure out how to set x-amz-meta- headers  on files/directories via s3cmd ? I am stuck on this? 
the alternative solution, using chmod doesn't work on new directories. so it's not better choice.

**Comment by ggtakec** [comment]
@wenhongqiang 
If you allow to ignore existing permissions, you can specify umask, mp_umask, gid and uid option for s3fs.
By these option, s3fs sets permission to all objects(files, directories) under mount point.
Please see man pages at s3fs and mount.

Thanks for your assistance.

**Comment by wenhongqiang** [comment]
@ggtakec 
thanks . will try it

**Comment by pelamfi** [comment]
For those unfamiliar how the options mentioned by @wenhongqiang work, here is an example `-o uid=1000,umask=077,gid=1000,...` . (Replace 1000 with your own numeric user id.)

**Comment by pifou42** [comment]
It's working, at last !  Thanks dudes.
I used the following command line (change the bucket and mount point names, btw)
`s3fs -o allow_other,uid=33,gid=33,umask=227,use_cache=/root/cache MY-BUCKET-NAME /mnt/MY-MOUNT-POINT`

- Where 33 is both my apache user and group.
- Note that I set mask to 227, which gives the opposite permissions, alias "550".
- Btw, don't forget to create the cache directory if you intend to use one.
  Also, while most the examples I found were using a cache dir, no one recommended to empty it sometimes.  I'll probably put a nightly cron to remove "old" files very soon, since I don't want my HDD to have my whole HDD filled.

I'm also wondering if the allow_other option is still necessary, but I suppose it is.  Gotta check this later.

**Comment by andrewgaul** [comment]
> Also, while most the examples I found were using a cache dir, no one recommended to empty it sometimes. I'll probably put a nightly cron to remove "old" files very soon, since I don't want my HDD to have my whole HDD filled.

#554 should address this.

**Comment by pkerpedjiev** [comment]
In case anybody is wondering, you can get your `uid` and `gid` by running the `id` command:

```
me@computer:~/tmp [develop|!]$ id
uid=502(me) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),399(com.apple.access_ssh),702(com.apple.sharepoint.group.2),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing)
```

**Comment by javilumbrales** [comment]
In case someone lands here using Mac and having the same issue, I managed to be able to read folders and files with the below command:

s3fs BUCKET_NAME /path/to/mount/ -o passwd_file=/path/to/credentials,allow_other,uid=`id -u`,umask=0077,mp_umask=0077,use_cache=/path/to/cache/ -d -d -f

**Comment by myfitment** [comment]
I'm trying to set this up in a chrooted environment. All subdirectories are 755 and they can't be changed with chmod. What is the command to alter subdirectories to 777?

**Comment by ggtakec** [comment]
We kept this issue open for a long time.

@myfitment Probabry you can use `umask` and `mp_umask` option for s3fs.
And if you need more information or reporting bugs, please open new issue.(This issue will be closed.)

**Comment by Signant** [comment]
Hi, 
We are using s3fs v1.82 and we are facing same issue permission read/write issue. what can be done to resolve this. are there any bugs in this version ?

**Comment by gaul** [comment]
@Signant please stop spamming random issues with the same comments.  Try upgrading to the latest s3fs.  I will lock this issue now.
