### ISSUE TITLE
Feature Request  Content-Encoding:gzip

### ISSUE THREAD

**Issue by lordtangent** [s3fs-fuse/s3fs-fuse#368]
How about support for automatic gzip compression and tagging with Content-Encoding:gzip ?

That would reduce the file sizes for many common file types including executables.

**Comment by tspicer** [comment]
+1

**Comment by RobbKistler** [comment]
I suspect the mapping of file-like access to object access (ranged GET's, S3 multipart PUT's) makes this difficult.

**Comment by ggtakec** [comment]
I think that it is difficult to dynamically compressed.

It is possible to compress upload after s3fs has accumulated in the temporary cache.
However, it is difficult to download. 
Because if you want to download by specifying the offset, you have to decompress it after you download all.
And, I think this would be inefficient.

Therefore, I recommend that you compress the object before uploading it.
(I think that it is not good way to compress by s3fs.)

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
I will close this, but if the problem persists, please reopen or post a new issue.
