### ISSUE TITLE
S3 bucket that creates Lambda events generates 2

### ISSUE THREAD

**Issue by cashgl** [s3fs-fuse/s3fs-fuse#390]
When I drop a file into my S3 bucket through an s3fs mount and events for my Lambda function get generated, there's always 2 identical ones that are created. Otherwise, uploading the file through the S3 gui just creates 1 event.

Setup isn't anything different from the instructions.

**Comment by ggtakec** [comment]
@cashgl 
When s3fs makes(updalods) the file(object) to S3, first s3fs makes zero file on S3 and second uploads it.
Thus it is probably the two events will generate.
This behavior is due to FUSE.
FUSE always creates a zero file or sets the file size to zero just before FUSE copies the file.
s3fs more than a FUSE-based, which can not be avoided.

Regards,

**Comment by ingageco** [comment]
@ggtakec  - So can we assume that when the second event fires, the upload is 100% complete?

**Comment by ingageco** [comment]
I'm dealing with large video files, so that's the context of my question.

**Comment by ggtakec** [comment]
@ingageco 
The first event(HTTP PUT) is for creating a file as 0 size.
The second's PUT event means that s3fs starts to upload the file contents, it does not finish to upload.probablyprobablyprobably
Probably, your application(ex. cp command) will be waited to finish to upload all of file constents.

Regards,

**Comment by ingageco** [comment]
@ggtakec Thank you for clarifying!
