### ISSUE TITLE
Does file creation really fail because of eventual consistency?

### ISSUE THREAD

**Issue by plufz** [s3fs-fuse/s3fs-fuse#399]
Hi!

I'm trying to understand this from the documentation "Due to S3's "eventual consistency" limitations file creation can and will occasionally fail.".

Is this really true? From what I understand of "eventual consistency" file writes never fails, they just take time to be available for read.

Will files I write to my s3 buckets fail or will it just take some time before I can read the files?

**Comment by ggtakec** [comment]
@plufz 
This is the content that describes "eventual consistency" of the S3.
You can find "Amazon S3 Data Consistency Model" in http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html
In other words, this is the sense that "eventual consistency" of s3fs is influenced by the S3.

I do not think that there is a large time lag on my experience.
I think, as long as the AWS can not explicitly a time lag, it is not know when not to try in your environment.

Regards,

**Comment by andrewgaul** [comment]
@plufz You can test this yourself using the eventual consistency middleware of S3Proxy:

https://github.com/andrewgaul/s3proxy/wiki/Middleware---eventual-consistency

I found that creating a file can fail because `s3fs_create` calls `create_file_object` which PUTs the object then immediately calls `get_object_attribute` which HEADs the object.  S3Proxy models the most pessimistic form of eventual consistency, read-after-create.  Only Amazon us-standard region with the default endpoint exhibits these semantics; other regions, including us-standard with the Virginia endpoint, do not.  Deleting, overwriting, or updating a file's metadata can exhibit eventually consistent behavior in all regions.  I explored eventual consistency semantics further here:

https://github.com/andrewgaul/are-we-consistent-yet

@ggtakec s3fs would benefit from removing excessive stat calls, including the `s3fs_create` function mentioned above.  This would improve performance and reduce the likelihood of users observing eventual consistency.

**Comment by ggtakec** [comment]
@andrewgaul Thanks for your help.
Although it is certainly redundant, I think that stat read(HEAD request) after the file creation(PUT) is required for confirmation of file initial creation.
But I will survey that it should be deleted in the future.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
I will close this, but if the problem persists, please reopen or post a new issue.
