### ISSUE TITLE
mounting via /etc/fstab 

### ISSUE THREAD

**Issue by chrisgo** [s3fs-fuse/s3fs-fuse#417]
Debian 8.3 x 64

Basic mounting via /etc/fstab results in the following error message `sudo mount -a`.  Any ideas on how to debug this further?

```
mount: wrong fs type, bad option, bad superblock on s3fs#s3fs-test.domain.com,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

Mounting via command line works

```
sudo s3fs s3fs-test.domain.com /mnt/s3fs-test -o allow_other -o passwd_file=/etc/passwd-s3fs -d -d -f -o f2 -o curldbg
```

_Note: s3fs is doing it's job trying to figure out the endpoint/region, bucket is on us-west-1_

Translating this to /etc/fstab as follows

```
...
s3fs#s3fs-test.domain.com	/mnt/s3fs-test	fuse	_netdev,allow_other	,dbglevel=dbg 0	0
...
```

Doing a `sudo tail -f /var/log/messages` and `sudo tail -f /var/log/syslod` does not show any error messages.  

* It almost seems like `sudo mount -a` cannot find `s3fs`?
* Tried `sudo apt-get install nfs-common` and `sudo apt-get install cifs-utils` with no luck
* How does the /etc/fstab find the `/etc/passwd-s3fs`, do you have to specify that in the options?

**Comment by nturner** [comment]
Do you have the "fuse" package installed?

**Comment by chrisgo** [comment]
@nturner yes, everything on here

```
sudo apt-get install automake autotools-dev g++ git libcurl4-gnutls-dev libfuse-dev libssl-dev libxml2-dev make pkg-config
```

**Comment by dsulli99** [comment]
Installing fuse solved this problem for me as well.

**Comment by dsl101** [comment]
This just bit me too, and took a while to track down. Could 'Check fuse is installed' be added to the home page readme in the fstab section?

**Comment by pifou42** [comment]
Note that for mounting via fstab, using the "fuse _netdev" option is **necessary.**  Else, it doesn't wait for the network connection before attempting to mount, and miserably fails.

Another more global note about s3fs : 
if you have locate and/or mlocate installed, you could be interrested in adding an exception, so that it does NOT scan your whole bucket.
On my Ubuntu 14.04, I had to modify both my /etc/updatedb.conf and /etc/cron.daily/locate, adding " /mnt/my-bucket-name" to PRUNEPATHS and " fuse.s3fs" to PRUNEFS

I suppose adding fuse.s3fs should've been enough, but I'll check that later.  I didn't want 1.4TB of 'cache' to fill up my HDD :)
