### ISSUE TITLE
Fuse 2.8.4 really required?

### ISSUE THREAD

**Issue by paulm17** [s3fs-fuse/s3fs-fuse#42]
Hi,

I'm using centos 6.5.  It comes with Fuse 2.8.3.

Is there any particular reason why fuse 2.8.4 is required?  Are there any problems with 2.8.3?

Thanks

**Comment by juliogonzalez** [comment]
I know this is an old issue, but for reference, since I am now packaging for Fedora and I need to reference this in relation to CentOS6:

Reading the original issue at Google Code doesn't make clear to me that the culprit was fuse, but anyway, right now the testsuite just doesn't pass anymore with fuse 2.8.3, even it seems the basic functionality still works:

```
PASS: test_append_file
PASS: test_truncate_empty_file
PASS: test_mv_file
PASS: test_mv_directory
PASS: test_redirects
PASS: test_mkdir_rmdir
PASS: test_chmod
PASS: test_chown
PASS: test_list
PASS: test_multipart_upload
PASS: test_multipart_copy
PASS: test_symlink
PASS: test_mtime_file
PASS: test_rm_rf_dir
PASS: test_write_after_seek_ahead
FAIL: test_truncate_file
FAIL: test_remove_nonempty_directory
FAIL: test_special_characters
FAIL: test_extended_attributes
SUMMARY for ./integration-test-main.sh: 15 tests passed.  4 tests failed.
Trying: grep -q s3fs-integration-test /proc/mounts
s3fs: [INF] s3fs.cpp:s3fs_destroy(3428): destroy
FAIL: small-integration-test.sh
==================
1 of 1 test failed
==================
make[1]: *** [check-TESTS] Error 1
```
