### ISSUE TITLE
new 1.80 release?

### ISSUE THREAD

**Issue by mapreri** [s3fs-fuse/s3fs-fuse#423]
what do you think about cutting a new release?  with 200+ commits since the last one and many fixes I guess it's getting overdue :wink:

**Comment by ggtakec** [comment]
Hi @mapreri 
Since the issues has been settled, I also was thinking that we should be the new release.
I will prepare a new release after confirming the last PR.
Please wait just a little bit later.

In the future, I would like to regularly release on a quarterly basis other than the patch release by the fatal problem.

Thanks for your help.
Takeshi.

**Comment by ggtakec** [comment]
@mapreri 
I made new release tag v1.80 and changed some files(ChangeLog and configure.ac) for new release.
Please checkout it and build new package.

Thanks in advance for your assistance.

**Comment by andrewgaul** [comment]
:+1: Quarterly releases.

**Comment by mapreri** [comment]
Great!  Thank you! :smile: 

@jollyroger do you think you can update the debian package for this? ^^

**Comment by mapreri** [comment]
[OT, but doesn't deserve a bug]

btw, the copyright headers on the file needs some love: your copyright (according to those headers) is still only for 2007-2013 :)

**Comment by ggtakec** [comment]
@mapreri Thank you for your notice.

Until the next release, I am going to change the Copyright of the source code header in the following format in order not to edit by each of the new year:

Copyright (c) [year] [name]

Thanks for your kindness.

**Comment by ggtakec** [comment]
Fixed format for year part of copyright by #587
