### ISSUE TITLE
Shell is freezing when s3fs is active

### ISSUE THREAD

**Issue by jsncrdnl** [s3fs-fuse/s3fs-fuse#445]
I'm working with a Ubuntu 14.04.3 LTS server on Amazon.

I succeeded in running f3fs on a folder at the root of my disk "/s3mnt".
I gave 770 rights to the user accessing that folder (with the s3fs command).

I'm able to mount my S3 bucket to that folder. The two "txt" files in my bucket are synced to the folder.
My problem is that whenever I run a command on that folder, my putty (ssh session) window is freezing...

In exemple, its freezing if I do (when s3fs is running):

> ls /s3mnt
> echo hellowolrd > /s3mnt/test3.txt

By the (it's probably related to another issue), I can't read or edit the files synced in that folder...

> cat /s3mnt/test3
> cat: /s3mnt/test3: No such file or directory

**Comment by tlevi** [comment]
These are related because it is not *really* freezing - just waiting a long time for the IO to complete while s3fs retries. This usually happens when s3fs can't connect properly - for example, authentication details are wrong.

Run s3fs in foreground with debug log in another terminal to find out what is wrong.

**Comment by tlevi** [comment]
Note this can seem a little counter-intuitive because it happily starts and backgrounds, so one may think it has succeeded. In reality it will fail to connect forever in the background, making any operations to the mount very very slow to fail.

**Comment by ggtakec** [comment]
I'm sorry for my late reply. We kept this issue open for a long time.

Is this problem continuing?
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.

I will close this, but if the problem persists, please reopen or post a new issue.

**Comment by sinnrrr** [comment]
@ggtakec this problem still exists. I can't even `cd` into the folder or `ls`, which contains a fuse-mounted one.

**Comment by sinnrrr** [comment]
@ggtakec I would be happy to provide you with this information, but my shell completely freezes, when I mention the FUSEd folder (I can't even `ctrl-c` or `ctrl-z` it)

https://user-images.githubusercontent.com/25615887/168802012-27a28513-9760-4a57-a61a-1b120425dfc8.mp4

**Comment by ggtakec** [comment]
@sinnrrr Thank you for the screen capture.

I would like to sort out a few issues regarding this matter.
It will take your time to do so, but could you please post your problem as a new issue?
(At that time, please add #445 as Related Issue to the body text. If you forget it, no problem because I will add it.)
This is because we want to know details on the prerequisites for this problem.
When posting, please describe the version of s3fs, boot options of s3fs, etc. I think those will be useful for the solution.

Going back to this posts, as far as I can see in your screen capture, it seems that s3fs is already up and maybe s3fs is doing some time-consuming processing for something or deadlocked.
Probably, even if you execute the df command that should be completed with the simplest processing, I think it will be in the same state.

I would like to know information such as s3fs startup, command contents, or S3 bucket status up to this state.
Thus you will stop s3fs and run it again with the option(dbglevel, curldbg) to output the debug information mentioned above.
It will be expected to output valuable information for us.
