### ISSUE TITLE
Cannot access files 'Operation not permitted'

### ISSUE THREAD

**Issue by dmelo** [s3fs-fuse/s3fs-fuse#470]
I have mounted my bucked, and the file ownership is attributed to root, moreover file permission is "000" and I cannot change it. I have another software (prerender) which is able to read and write on that bucket with the same credentials. So, I believe there must be something wrong with my setup or it is a bug

``` bash
dmelo@merov2:~/proj2/s3fs-fuse$ mkdir ../g2m2-us-prerender &&  ./src/s3fs g2m2-us-prerender ../g2m2-us-prerender -o passwd_file=passwd 
dmelo@merov2:~/proj2/s3fs-fuse$ cd ../
dmelo@merov2:~/proj2$ cd g2m2-us-prerender/
dmelo@merov2:~/proj2/g2m2-us-prerender$ ls
http:
dmelo@merov2:~/proj2/g2m2-us-prerender$ cd 'http:'
bash: cd: http:: Operation not permitted
dmelo@merov2:~/proj2/g2m2-us-prerender$ ls -lhat
total 17K
drwxr-xr-x 267 dmelo dmelo 16K Sep 18 15:18 ..
drwx------   1 dmelo dmelo   0 Dec 31  1969 .
d---------   1 root  root    0 Dec 31  1969 http:
dmelo@merov2:~/proj2/g2m2-us-prerender$ find
.
./http:
find: ‘./http:’: Operation not permitted

```

I'm on commit a56fe0ea283216cfeb78143155d8024b4aa137d7, using fedora with fuse-devel-2.9.7-1.fc24.x86_64

I have started s3fs-fuse in debug. The output is on this gist https://gist.github.com/dmelo/f0faf40356ff26150f71a1dec507a668

**Comment by ggtakec** [comment]
@dmelo 
The reason is that the direcotry(http:) does not have a attribute for using s3fs.

s3fs decides the file permission(uid/gid/mode/xattr) by "x-amz-meta-*" HTTP header which are had each file object.
These header are also required for the directory objects.

Thus your directory object does not have these, so s3fs can not decide file mode. And it supposed to be displayed as 000.

To work around this problem, you have two following way.
1) adding http headers to objects(by s3fs, s3console, s3cmd, etc)
2) run s3fs with umask option(and uid/gid if you needs)

Please try it.
Regards,

**Comment by gaul** [comment]
1.85 includes new permission defaults.  Please test with it and reopen if symptoms persist.
