### ISSUE TITLE
error while mounting s3 in linux 6.3

### ISSUE THREAD

**Issue by saikat891** [s3fs-fuse/s3fs-fuse#479]
[root@*\* s3fs-fuse]# make
make  all-recursive
make[1]: Entering directory `/root/s3fs-fuse/s3fs-git/s3fs-fuse'
Making all in src
make[2]: Entering directory`/root/s3fs-fuse/s3fs-git/s3fs-fuse/src'
g++ -DHAVE_CONFIG_H -I. -I..  -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -I/usr/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT s3fs.o -MD -MP -MF .deps/s3fs.Tpo -c -o s3fs.o s3fs.cpp
**s3fs.cpp: In function ‘int main(int, char**)’:
**s3fs.cpp:4962: error: invalid conversion from ‘int (_)(const char_, const char_)’ to ‘int (_)(const char_, const char_, unsigned int)**’**
make[2]: **\* [s3fs.o] Error 1
make[2]: Leaving directory `/root/s3fs-fuse/s3fs-git/s3fs-fuse/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/root/s3fs-fuse/s3fs-git/s3fs-fuse'
make: **\* [all] Error 2

**Comment by ggtakec** [comment]
@saikat891 I'm sorry for late reply.
What version of libfuse do you use(install)?
It seems that you use latest libfuse(3.x) which is not stabled yet, please use libfuse 2.9.x.
I think this issue is as same as #469.
Please install(or setup) libfuse 2.9.x and try to build s3fs.

Thanks in advance for your assistance.
Regards,
