### ISSUE TITLE
mount point ctime

### ISSUE THREAD

**Issue by liuyuhong66** [s3fs-fuse/s3fs-fuse#528]
when i mount the dir，the dir create time is strange，just like this。
drwx------ 1 root root    0 Jan  1  1970 mount_point

- Version of s3fs being used V1.80
 
- Version of fuse being used  2.9.2

- System information 3.10.0-327.el7.x86_64

**Comment by ggtakec** [comment]
@liuyuhong66 
s3fs can not determine mount point permissions, it will display like this.
(uid/gid is set effective s3fs executing user uid/gid for the default)
This is because bucket does not have header x-amz-meta-*, so user/group/time can not be specified.
Thus mount point ctime is unixtime=0 now.
Regards,

**Comment by liuyuhong66** [comment]
thank you very much。
I tried allow_other and umask， it works well
