### ISSUE TITLE
_$folder$ configuration

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#571]
s3fs stores directory metadata in one of two formats: name + trailing `_$folder$` and `/`.  I believe the former exists before Amazon recommended the latter.  Some systems like B2 and minio cannot support the latter.  s3fs issues extra RPCs to probe the object store in case one or the other exists.  We should consider adding a configuration knob for which format to use to avoid the extra RPCs.  This behavior dates back to 36447a23eb46089bf59df8c26dfb6f045c10e88b to support s3fox.

**Comment by ggtakec** [comment]
I added new option "notsup_compat_dir" to master branch.(#579)
It is an option to disable checking of s3fs compatible directory objects.
If it is a bucket created with s3fs (only s3fs may be used) it will work without problems.

However, I do **not recommend** this option.
This is because it is assumed that it does not include uploaded objects using s3cmd, s3 console, or other tools.
If s3fs can not recognize the directory object, the user will lose convenience.

However, for users who wish to reduce the cost of communication more than that, they can use it at their own risk.

@andrewgaul @sqlbot
Please tell me your opinion.

**Comment by gaul** [comment]
Resolved.
