### ISSUE TITLE
s3fs have crashed with a segfault

### ISSUE THREAD

**Issue by timurb** [s3fs-fuse/s3fs-fuse#6]
I've seen the s3fs segfault today in the morning with the following message:
```
Jan 13 03:29:56 monitoring kernel: [1322370.223444] s3fs[7788]: segfault at 0 ip 00000000004275db sp 00007f2660b7d7c0 error 4 in s3fs[400000+4b000]
```
There are no accompanying messages in logs but I know there was some minor writing to S3 ~5min in advance to that.

The s3fs daemon was running since 9 Jan with more than 1.5Tb written since that time. Before that I've tried running s3fs of the same version on the same host with no errors (but with lesser overall throughput I think) for 2 weeks (before that I've used the older 1.61 version).

I'm running Debian Wheezy 7.3 with s3fs 1.74 (I think I've used r499 for compilation):
```
root@monitoring:~# s3fs --version
Amazon Simple Storage Service File System 1.74
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by ggtakec** [comment]
I'm sorry about this Issue had been left at a long period of time.

Latest codes(master branch) is fixed some bugs which included like this issue.
And I think that it is difficult to reproduce this problem now because there are many fixes from posting this issue.

If you is in still the same defect has failed on latest codes, please post new issue.
And If you post new problem, please post with detail logs(ex. syslog/messages) which are made by running s3fs with "dbglevel" or "curldbg".

Thanks in advance for your help.
