### ISSUE TITLE
dbglvl=dbg causes uploads to grind to a halt after ~10 seconds

### ISSUE THREAD

**Issue by thomasv314** [s3fs-fuse/s3fs-fuse#613]
Hi,

I'm not totally sure if this is as intended or not, but figured it may be worth reporting anyway. 

We've been using s3fs as an S3<->SFTP bridge for quite some time now. In debugging an unrelated issue we recently ran s3fs with `dbglvl=dbg`. After resolving the issue, we noticed that connections would grind to a halt after about 10 seconds of uploading a file. 

With dbglvl on, we saw 2.5mbs -> 10 seconds later, 30kbs.
With dbglvl unset, we saw 2.5mbs -> for the entire upload.

If this isn't a bug, hopefully this helps other people debug slow s3fs connections 😄 

#### Additional Information
- Version of s3fs being used (s3fs --version)
  - Amazon Simple Storage Service File System V1.82(commit:620f6ec) with OpenSSL
  - Also confirmed/experienced this w/ v1.80
- Version of fuse being used (pkg-config --modversion fuse)
  - 2.9.2

- System information (uname -a)
  - Linux ip-10-125-100-208 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Distro (cat /etc/issue)
  - Ubuntu 14.04.4 LTS

- s3fs command line used (if applicable)
```
/usr/local/bin/s3fs foobar-stage-sftp /home/foobar -o rw,nosuid,allow_other,nodev,use_cache=/tmp/s3_cache,iam_role=foobar-stage-s3ftp
```

**Comment by ggtakec** [comment]
What do you set the `dbglevel` option?

The `dbglevel` option can be set crit (critical), err (error), warn (warning), info (information) or dbg (debug).
I think s3fs will be slower from `crit` to` dbg`.
Especially a case of `dbg`,  when uploading/downloading a file, a message is output for each copy operation to a temporary file, which is quite expensive.
I think that the `info` value is enough for normally debugging, then if you are concerned about slow speed, it is better to use `info` instead of` dbg`.
Also, the `curldbg` option will affect performance.
