### ISSUE TITLE
Cannot make a directory through php inside mounted s3 bucket

### ISSUE THREAD

**Issue by MariusStanciu95** [s3fs-fuse/s3fs-fuse#657]
I have successfully mounted the s3 with the **-o allow_other** option and also having **allow_other** enabled in my fuse.conf file. Inside my bucket I have 2 directories.

I am using Laravel and I am trying to copy images inside my bucket and arranging them in different folders.

The issue is that in the first directory of the bucket , i can successfully write images, however , in the second one I cannot make a directory through 
**mkdir(pathToMntS3/folderName,0777,true)**
php command.

Has anybody encountered this? Thanks in advance.

**Comment by ggtakec** [comment]
@MariusStanciu95 
If you execute s3fs directly, please tell us the parameters for s3fs.
Otherwise, if you are writing an entry in fstab, please tell us it.

And if you can reproduce the problem, please try logging by adding "dbglevel", "curldbg" etc. to s3fs options.
(You can see detail of the options in man s3fs)
Those logs will be useful for us to solve the problem.
Regards,

**Comment by gaul** [comment]
Closing due to lack of response.
