### ISSUE TITLE
/usr/src/s3fs-fuse# ./autogen.sh

### ISSUE THREAD

**Issue by Amritmatti** [s3fs-fuse/s3fs-fuse#723]
./configure: line 4972: syntax error near unexpected token `common_lib_checking,                                                                                        '
./configure: line 4972: `PKG_CHECK_MODULES(common_lib_checking, fuse >= ${min_fu                                                                                        se_version} libcurl >= 7.0 libxml-2.0 >= 2.6 )'

i'm facing this problem plz help

**Comment by nmgeek** [comment]
Try this:

```
sudo apt-get update
sudo apt-get install automake
rm configure
./autogen.sh
./configure
```

This error happened to me also.  While I can't completely back up to see how it happened it seems like I had an old apt repo configuration (because I had not run apt-get update in months) and an old version of automake was installed.  It was missing one program which caused a broken instance of the configure script to be created.  The broken configure script has the error shown in the first comment, above.

**Comment by Fyb3roptik** [comment]
I am getting the same thing. This did not fix it for me

**Comment by gaul** [comment]
Could you share your operating system?  This should work for Ubuntu 16.04 and newer.

**Comment by bbxiao1** [comment]
I’m seeing this also on Manjaro.

**Comment by bbxiao1** [comment]
FWIW my issue was solved by installing `pkgconf`

**Comment by gaul** [comment]
Please try the suggested workaround and reopen the issue if symptoms persist.
