### ISSUE TITLE
Fail to mount digitalocean spaces onto droplet

### ISSUE THREAD

**Issue by chengjk84** [s3fs-fuse/s3fs-fuse#751]
I am using same method mounting space to droplet few month ago it work... but today i do it on new droplet and it keep failing with error saying "Must specify the bucket= mount option"

#### Version of s3fs being used (s3fs --version)
_fuse-s3fs-0.9-10.fc27.noarch_

#### Version of fuse being used (pkg-config --modversion fuse)
_fuse-2.9.7-9.fc27.x86_64_

#### System information (uname -r)
_4.15.14-300.fc27.x86_64_

#### s3fs command line used (if applicable)
```
s3fs swarm-space-sgp1 /mnt/swarm-space-sgp1 -o url=https://sgp1.digitaloceanspaces.com
```
#### /etc/fstab entry (if applicable): 
```
s3fs#swarm-space-sgp1 /mnt/swarm-space-sgp1 fuse allow_other,_netdev,nosuid,nodev,url=https://sgp1.digitaloceanspaces.com 0 0
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
Apr 20 05:22:33 dev-n-devops-swarm-01.localdomain s3fs[938]: Must specify the bucket= mount option
```

**Comment by ggtakec** [comment]
@chengjk84 
If you are using the fuse-s3fs package, not the s3fs-fuse package, we are sorry for that we do not know the meaning of the error.
If you are going to use s3fs-fuse, please look for the package s3fs-fuse-1.83 and install it.

Since digitalocean is said to be compatible with AWS S3, it probably works.
If it does not work, you can specify the option(dbglevel = dbg) when starting s3fs(s3fs-fuse) and get/look at the log.

I hope you can connect to digitalocean using s3fs-fuse.

**Comment by gaul** [comment]
Closing since issue encountered with fuse-s3fs and not s3fs-fuse.
