### ISSUE TITLE
i have some problems about how to checkout my backup

### ISSUE THREAD

**Issue by linux0x5c** [s3fs-fuse/s3fs-fuse#846]
Issue1: I used to use s3fs mounts the bucket on my system, if I use cp or tar and other tools to backup my system, I don't know how to judge, my backup is complete transmission to the aws s3, is there any way I can go to judgment, such as through HTTP code or any other return value, the etag method seems not very common, for multiupload etag md5 value is not the object.

Issue2: I didn't understand max_stat_cache_size in the option, but what cache does that mean? Can you give me an example?

I am looking forward to your answer. Thank you very much.

**Comment by gaul** [comment]
Issue 1: could you just check the exit code of `cp` via `echo $`?  It will be non-zero if an error occurred.

Issue 2: s3fs caches object metadata from S3 since fetching it can take a hundred milliseconds or more.  Access is instantaneous when the entry is present in the cache.  To limit memory use, s3fs limits the maximum number of entries.  This cache is ephemeral and repopulates when s3fs restarts.

**Comment by linux0x5c** [comment]
I had getted it,thanks for your answer.
