### ISSUE TITLE
What is the status of "-o prefix" ?

### ISSUE THREAD

**Issue by kallu** [s3fs-fuse/s3fs-fuse#87]
s3fs man-page has this prefix -option

-o prefix (default="") (coming soon!)
              a prefix to append to all S3 objects.

What is the status of this feature and is there an estimate when "soon" would be?

**Comment by ggtakec** [comment]
I fixed #103 for this issue.

Description of Prefix option was written when the man page of s3fs has been created.
Maybe, I think that this option was trying to prepare for mount to specify the directory path under just  BUCKET.
Now, because it is a specified directory path in the specified s3fs command line, it is not required.
ex) s3fs bucket: /directory ... mountpoint options

Therefore, I have removed the description from the man page of prefix options.

Thanks very much.
(I closed this issue)

**Comment by basz** [comment]
does this mean this feature is not coming back?
