### ISSUE TITLE
option use_ino does not work properly

### ISSUE THREAD

**Issue by snowbird29** [s3fs-fuse/s3fs-fuse#90]
Hello,

I want to make use of the option "use_ino" for the following purpose

File
size: 909
atime: 1416321754
mtime: 1416321754
ctime: 1416321754

S3
size: 919
atime: 0
mtime: 1417438347
ctime: 0

As you can see "atime" and "ctime" are 0 using S3FS, I would like to see the File output above.

Would that be possible ? I'm using V1.78

I need a fast response, thank you.

**Comment by ggtakec** [comment]
I'm sorry for replying late.

I think that it is possible to add those, but we need to be careful to add those.
Means to add them, means that of adding the HTTP header (x-amz-xxxx) for each s3 object.
s3fs makes http header for ctime at first time, when s3fs creates(puts) new object.
But for atime s3fs puts new http header value when s3 object is read through s3fs(fuse), so it may be high costs and lower performance.
Because the cache for stats and object will not be used.

So I think that it is hard to support a time on s3fs.

Regrads,

**Comment by ggtakec** [comment]
I understand that the files(directories) should have atime/ctime, but I have decided not to add it current situation.
Because atime must be updated every read access, s3fs performance is an issue and it can not be updated when it is cached.
For ctime, rather than for the update the same inode as the file system, because the object itself is replaced, I can not determine the correct way.
Therefore, I decided to not to specification changes s3fs.

I'm closing this issue, if you have more problem, please post new issue or reopen this issue.

Thanks in advance for your kindness.
